first time
funcZero
funcOne(1)
funcTwo(1, 2)
funcError
caught Error: from funcError as expected

second time
before
funcZero
after
before
funcOne(1)
after
before
funcTwo(1, 2)
after
before
funcError
error
caught Error: from funcError as expected
